Add worldview page and route
AmbrusStudio/Website pull request #1
Opened 2022-07-04 23:49 UTC by imbillow

2022-07-04 23:53 UTC, imbillow commented
Preview

![image](https://user-images.githubusercontent.com/24983369/177226340-a2831d86-a67c-4c0c-abc8-497ada3a2748.png)

2022-07-05 03:41 UTC, Garfield550 commented on index.html
> -  <head>
不要格式化这个文件

2022-07-05 03:41 UTC, Garfield550 commented on src/views/world/RangerView.vue
> +  background: url('/src/assets/images/女武士2 1.png') center no-repeat;
图片文件请分类并且用纯英文

2022-07-05 03:46 UTC, Garfield550 requested changes
上面的是要修改的，这里的是建议。

Vue `<script>` 部分可以试试用 ts 写，以及新的 `Composition API` 方式，对于字体设置，Montserrat Teko 和 Zen Kaku Gothic New 都可以用 UnoCSS 来做，具体可以看 `vite.config.ts` 文件。

2022-07-12 05:41 UTC, closed without merging